### ISSUE TITLE
config/ebay_client.yml with Environment Variables

### ISSUE THREAD

**Issue by guillosaracco** [kayoom/ebay_client#13]
Hi,
Thanks for a great gem!

My only issue is that I would like to hide my eBay credentials and use environment variables instead and I'm having a hard time doing so...

This is what I would like to end up with:

```yml
development: &sandbox
  api_keys:
    - token: <%= ENV['EBAY_TOKEN'] %>
      devid: <%= ENV['EBAY_DEVID'] %>
      appid: <%= ENV['EBAY_APPID'] %>
      certid: <%= ENV['EBAY_CERTID'] %>

test:
  <<: *sandbox

production:
  api_keys:
    - token: <%= ENV['EBAY_TOKEN'] %>
      devid: <%= ENV['EBAY_DEVID'] %>
      appid: <%= ENV['EBAY_APPID'] %>
      certid: <%= ENV['EBAY_CERTID'] %>
```

Any help would be appreciated.
Thank you!
